### ISSUE TITLE
A little beautification

### ISSUE THREAD

**Issue by ekrogh** [NdubuisiJr/skia-chart#15] opened 2020-06-23 11:13 UTC
Hi

I have tested skia-chart on Android, UWP and macOS. It works really well!

In my copy of skia-chart I have made a couple of changes that I think makes it look better on my devices. I have attached a diff of the files I have changed and the changed files.

Best
Eigil
[skia-chart-diff.zip](https://github.com/NdubuisiJr/skia-chart/files/4818939/skia-chart-diff.zip)

**Comment by NdubuisiJr** [comment] 2020-06-26 09:59
Hi @ekrogh 

I would really appreciate a pull request, let's review your changes together and see if it is something we can merge.

Thanks

**Comment by ekrogh** [comment] 2020-06-26 16:22
You can clone/pull my version from my repos at
[https://dev.azure.com/ekrogh/skiaChartEks/_git/SkiaChart](url)

or

Should I push my changes to your github skia-chart repos ?
If so should i make my changes in a new branch?

Best regards
 Eigil

**Comment by NdubuisiJr** [comment] 2020-06-26 19:02
Hi Eigil.

Yes. I would prefer you to push to a new branch on the skia-chart repo. But the problem is that you can't directly do a push to the repo. You can do it indirectly via a pull request. I have outlined how you can do this in the README.MD file. Please take a look at [contributing](https://github.com/NdubuisiJr/skia-chart/blob/master/README.md#contributing).

I recently updated the procedure for contributing. 

I'm expecting your pull request.

Thanks and Best Regards

**Comment by ekrogh** [comment] 2020-06-27 12:49
Will do that as soon as possiblE

Eigil

**Comment by ekrogh** [comment] 2020-06-29 11:10
Created the pull request back to main repository.

Best

**Comment by NdubuisiJr** [comment] 2020-06-29 12:59
Okay cool...
I'll go through it and test

Thanks

**Comment by NdubuisiJr** [comment] 2020-06-29 18:07
I've merged your work!.

Thanks for contributing

**Closed** 2020-06-29 18:08 UTC

**Comment by ekrogh** [comment] 2020-07-21 18:15
Hello Ndubuisi Jr Chukuigwe,

 

I have made a pull back to the main repository of some changes I made.

 

·         LabelTextSize is now bindable

 

·         Added new bindable property, LegendItemSpacing

 

·         Added .GTK project and screen dumps of gtk windows.

 

·         Changes to make Legend show on all platforms

 

·         Label text formatting.

 

 

 

Best regards,

 

Eigil Krogh Sorensen

 

Stendalen 70A

8850 Bjerringbro

Denmark

 

e-mail:

eigilkrogh@gmail.com
